# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Will Oakley, Applied Math PhD Student'
tagline:          'Website for Will Oakley'
description:      'Research and business website for Will Oakley'
url:              'http://willoak.com'
baseurl:          'willoak.com'

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'Will Oakley'
linkedin:       'https://www.linkedin.com/pub/william-oakley/98/9b7/418'
twitter:        'https://twitter.com/yfitset'
facebook:       'https://www.facebook.com/wgoakley'
gplus:          'https://plus.google.com/u/2/106898968362854912138/about/p/pub'

# Google Analytics
gahandler: 'UA-53655642-1'

# Disqus
disqushandler: 'wgoakley'

# Blog Configurations
paginate: 3 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.6
